### ISSUE TITLE
How to write the "field" for an association, say `belongs_to`?

### ISSUE THREAD

**Issue by peaceful-james** [elixir-typed-structor/typed_structor#14]
If I have an ecto schema like this:

```
  schema "comments" do
    belongs_to :post, Post
  end
```

then how should I defined the `typed_structor`?

I assumed it would be like this:

```
  typed_structor do
    field :post, Post.t()
  end
 ```
 
 But this is creating dialyzer errors, since the `post` field may be `Ecto.Association.NotLoaded`.
 
 If you can, please provide an example typed structor with a field that is a `belongs_to` assoc.
 
 Thanks!

**Comment by fahchen** [comment]
In our projects, we handle this by using a union of `Post.t()` with `Ecto.Association.NotLoaded.t()`. Here’s an example:

```elixir
typed_structor define_struct: false do
  field :post, Post.t() | Ecto.Association.NotLoaded.t()
end
```

**Comment by peaceful-james** [comment]
That is good to know. I did the exact same thing to make this library work.

Can we keep this issue open? I think the current solution is not good enough for long-term widespread adoption. With the issue open, hopefully I will revisit this in the future with the aim of making a more concise solution.

**Comment by fahchen** [comment]
@peaceful-james I’d like to understand why you feel this solution isn’t sufficient. If we were to use raw typespecs, how would you declare the type for the Comment schema, especially considering the post association?

**Comment by peaceful-james** [comment]
I put an idea here: https://github.com/elixir-typed-structor/typed_structor/pull/15

**Comment by fahchen** [comment]
@peaceful-james I understand your concern.

To keep this package focused, we've introduced a plugin system. You can learn more about it in our documentation [here](https://hexdocs.pm/typed_structor/introduction.html). We've implemented several plugins that are ready for copy-and-paste, and you can find examples in the documentation.

To address the problem you've raised, we can add `belongs_to` and `has_many` association macros. This is also illustrated in the example provided by [TypedStructor.Plugin](https://hexdocs.pm/typed_structor/TypedStructor.Plugin.html#module-example).

Based on the example, you can tweak the `__ecto_type_to_type__` function to handle `belongs_to` and `has_many` associations like this:

```elixir
# snip
def __ecto_type_to_type__({:has_many, module}), do: quote(do: [unquote(module).t()] | Ecto.Association.NotLoaded.t())
def __ecto_type_to_type__({:belongs_to, module}), do: quote(do: unquote(module).t() | Ecto.Association.NotLoaded.t())
```

This approach allows you to define the `Ecto.Schema` while also defining the types. If you prefer to define the `Ecto.Schema` separately, you can remove the `after_definition` macro from the plugin.

Lastly, you can register the plugin globally to avoid importing it in every module. For more details, see [here](https://hexdocs.pm/typed_structor/registering_plugins_globally.html).

**Comment by peaceful-james** [comment]
Thank you! That is perfect.
